version: 0.1
# In the Resources section specify the name, alias, 
# target version, and (optional) the current version of your AWS Lambda function. 
Resources:
  - signup: # Replace "MyFunction" with the name of your Lambda function 
      Type: AWS::Lambda::Function
      Properties:
        Name: "sign-up" # Specify the name of your Lambda function
        Alias: "sign-up" # Specify the alias for your Lambda function
        CurrentVersion: "1" # Specify the current version of your Lambda function
        TargetVersion: "1"