version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo Downloading Go packages...
      - go get -u ./...
      - echo Testing Go code...
      - go test
      - echo Building the Go code...
      - GOOS=linux GOARCH=amd64 go build -o application application.go
artifacts:
  files:
    - application
    - appspec.yml